name: Daily REE Scraper

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 01:30 UTC
  workflow_dispatch:       # Optional manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install selenium

      - name: Install Chromium & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Verify Chromium and Chromedriver paths
        run: |
          which chromium-browser || true
          which chromium || true
          which chromedriver
          chromium --version || true
          chromedriver --version

      - name: Run REE Scraper
        run: python Scripts/download_demand.py
